apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredresources
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredResources
      validation:
        openAPIV3Schema:
          type: object
          properties:
            limits:
              type: array
              items:
                type: string

  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8srequiredresources

      # Check Pod trực tiếp
      violation[{"msg": msg}] {
        container := input.review.object.spec.containers[_]
        required := input.parameters.limits[_]
        not container.resources.limits[required]
        msg := sprintf("container <%v> missing limit <%v>", [container.name, required])
      }


      violation[{"msg": msg}] {
        container := input.review.object.spec.template.spec.containers[_]
        required := input.parameters.limits[_]
        not container.resources.limits[required]
        msg := sprintf("container <%v> missing limit <%v>", [container.name, required])
      }