apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: k8s-db-secret # Tên Secret tạo ra trong K8s
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: prod/db-password # Key trên AWS Secrets Manager